#!/bin/bash
# MR Title Validator - Validates merge request titles against conventional commits format
# Generated by ci-validation-script-generator skill

set -e

# ANSI Color Codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'  # No Color

# Check if running in MR/PR context
if [ -z "$CI_MERGE_REQUEST_TITLE" ]; then
  echo -e "${YELLOW}⚠ Not in merge request context. Skipping validation.${NC}"
  exit 0
fi

# Conventional commits pattern
PATTERN="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .+"

echo -e "${CYAN}=== MR Title Validation ===${NC}"
echo "Title: $CI_MERGE_REQUEST_TITLE"
echo ""

# Validate MR title
if echo "$CI_MERGE_REQUEST_TITLE" | grep -Eq "$PATTERN"; then
  echo -e "${GREEN}✅ MR title is valid!${NC}"
  echo -e "${GREEN}Format matches conventional commits specification.${NC}"
  exit 0
else
  echo -e "${RED}❌ MR title is invalid!${NC}"
  echo ""
  echo -e "${BLUE}Expected format:${NC} <type>(<scope>): <description>"
  echo ""
  echo -e "${BLUE}Examples:${NC}"
  echo "  feat(auth): add JWT authentication"
  echo "  fix(sale): resolve discount calculation bug"
  echo "  docs: update API documentation"
  echo "  refactor(core): simplify service layer"
  echo ""
  echo -e "${BLUE}Valid types:${NC}"
  echo "  feat     - A new feature"
  echo "  fix      - A bug fix"
  echo "  docs     - Documentation only changes"
  echo "  style    - Code style changes (formatting, white-space)"
  echo "  refactor - Code refactoring without changing functionality"
  echo "  perf     - Performance improvements"
  echo "  test     - Adding or updating tests"
  echo "  build    - Build system or external dependency changes"
  echo "  ci       - CI/CD configuration changes"
  echo "  chore    - Other changes that don't modify src or test files"
  echo "  revert   - Reverts a previous commit"
  echo ""
  echo -e "${RED}Your title: '$CI_MERGE_REQUEST_TITLE'${NC}"
  echo ""
  echo -e "${YELLOW}Note:${NC} The MR title will become the commit message when squash merging."
  echo -e "${YELLOW}Ensure it follows conventional commits format for automated changelog generation.${NC}"
  exit 1
fi
