#!/bin/bash
#
# AI Flow Runner Script
# Generic runner for Claude Code AI workflows in CI/CD
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_debug() {
    if [ "${CLAUDE_DEBUG:-false}" = "true" ]; then
        echo -e "${BLUE}[DEBUG]${NC} $1"
    fi
}

# Usage information
usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

AI Flow Runner for Claude Code in GitLab CI/CD

OPTIONS:
    -p, --prompt PROMPT         Prompt for Claude Code (required)
    -o, --output FILE           Output file for AI response (default: ai_output.md)
    -l, --log FILE              Log file for execution logs (default: ai_execution.ai.log)
    -m, --mode MODE             Permission mode: viewOnly, acceptEdits (default: viewOnly)
    -t, --tools TOOLS           Comma-separated allowed tools (default: Read(*) Grep(*) Glob(*))
    --post-to-mr                Post results as MR comment
    --mr-title TITLE            Title for MR comment (default: "AI Analysis")
    -h, --help                  Show this help message

ENVIRONMENT VARIABLES:
    ANTHROPIC_API_KEY           Claude API key (required)
    CI_MERGE_REQUEST_IID        GitLab MR ID for posting comments
    CI_PROJECT_ID               GitLab project ID
    CI_API_V4_URL               GitLab API URL
    CI_JOB_TOKEN                GitLab job token
    CLAUDE_MODEL                AI model (default: claude-sonnet-4)
    CLAUDE_DEBUG                Enable debug output (true/false)

EXAMPLES:
    # Simple code review
    $0 -p "Review this MR for code quality" -o review.md

    # Architecture analysis with MR comment
    $0 -p "Analyze architecture" -o arch.md --post-to-mr --mr-title "Architecture Analysis"

    # Code generation with write permissions
    $0 -p "Generate tests" -o tests.md -m acceptEdits -t "Read(*) Write(*) Edit(*)"

EOF
    exit 0
}

# Parse arguments
PROMPT=""
OUTPUT_FILE="ai_output.md"
LOG_FILE="ai_execution.ai.log"
PERMISSION_MODE="viewOnly"
ALLOWED_TOOLS="Read(*) Grep(*) Glob(*)"
POST_TO_MR=false
MR_TITLE="AI Analysis"

while [[ $# -gt 0 ]]; do
    case $1 in
        -p|--prompt)
            PROMPT="$2"
            shift 2
            ;;
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -l|--log)
            LOG_FILE="$2"
            shift 2
            ;;
        -m|--mode)
            PERMISSION_MODE="$2"
            shift 2
            ;;
        -t|--tools)
            ALLOWED_TOOLS="$2"
            shift 2
            ;;
        --post-to-mr)
            POST_TO_MR=true
            shift
            ;;
        --mr-title)
            MR_TITLE="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# Validate required arguments
if [ -z "$PROMPT" ]; then
    log_error "Prompt is required (-p or --prompt)"
    usage
fi

if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
    log_error "ANTHROPIC_API_KEY environment variable not set"
    exit 1
fi

# Setup MCP server if enabled
if [ "${GITLAB_MCP_ENABLED:-true}" = "true" ]; then
    log_info "Setting up GitLab MCP server..."
    if [ -f ci/scripts/mcp-server-setup.sh ]; then
        ci/scripts/mcp-server-setup.sh || log_warn "MCP server setup failed, continuing without MCP"
    else
        log_warn "mcp-server-setup.sh not found, skipping MCP setup"
    fi
fi

# Run Claude Code
log_info "Starting AI flow with Claude Code..."
log_debug "Model: ${CLAUDE_MODEL:-claude-sonnet-4}"
log_debug "Permission mode: $PERMISSION_MODE"
log_debug "Allowed tools: $ALLOWED_TOOLS"

claude \
    -p "$PROMPT" \
    --permission-mode "$PERMISSION_MODE" \
    --allowedTools "$ALLOWED_TOOLS" \
    ${CLAUDE_DEBUG:+--debug} \
    > "$OUTPUT_FILE" 2> "$LOG_FILE"

CLAUDE_EXIT_CODE=$?

if [ $CLAUDE_EXIT_CODE -ne 0 ]; then
    log_error "Claude Code execution failed with exit code $CLAUDE_EXIT_CODE"
    cat "$LOG_FILE"
    exit $CLAUDE_EXIT_CODE
fi

log_info "✅ AI flow completed successfully"
log_info "Output saved to: $OUTPUT_FILE"
log_info "Logs saved to: $LOG_FILE"

# Post to MR if requested
if [ "$POST_TO_MR" = true ]; then
    if [ -z "${CI_MERGE_REQUEST_IID:-}" ]; then
        log_warn "CI_MERGE_REQUEST_IID not set, skipping MR comment"
    elif [ ! -f "$OUTPUT_FILE" ]; then
        log_warn "Output file not found, skipping MR comment"
    else
        log_info "Posting results to MR !${CI_MERGE_REQUEST_IID}..."

        # Prepare MR comment body
        MR_BODY="## $MR_TITLE

$(cat "$OUTPUT_FILE")

---
*Generated by Claude Code in pipeline [#${CI_PIPELINE_ID}](${CI_PIPELINE_URL})*"

        # Post comment to GitLab
        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" \
            --header "Content-Type: application/json" \
            --data "$(jq -n --arg body "$MR_BODY" '{body: $body}')" \
            "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}/notes")

        if [ "$HTTP_STATUS" = "201" ]; then
            log_info "✅ Results posted to MR !${CI_MERGE_REQUEST_IID}"
        else
            log_warn "⚠ Failed to post to MR (HTTP $HTTP_STATUS)"
        fi
    fi
fi

log_info "AI flow runner completed"
