#!/bin/bash
#
# MCP Server Setup Script
# Configures GitLab MCP server for Claude Code integration
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check required environment variables
if [ -z "${CI_JOB_TOKEN:-}" ]; then
    log_error "CI_JOB_TOKEN not set"
    exit 1
fi

if [ -z "${CI_API_V4_URL:-}" ]; then
    log_error "CI_API_V4_URL not set"
    exit 1
fi

# Create .claude-code directory
CLAUDE_DIR=".claude-code"
mkdir -p "$CLAUDE_DIR"

log_info "Setting up GitLab MCP server configuration..."

# Create MCP server configuration
cat > "$CLAUDE_DIR/mcp-config.json" <<EOF
{
  "mcpServers": {
    "gitlab": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-gitlab"
      ],
      "env": {
        "GITLAB_PERSONAL_ACCESS_TOKEN": "${CI_JOB_TOKEN}",
        "GITLAB_API_URL": "${CI_API_V4_URL}"
      }
    }
  }
}
EOF

# Create Claude Code configuration
cat > "$CLAUDE_DIR/config.yml" <<EOF
# Claude Code Configuration
# Auto-generated by CI/CD pipeline

mcp:
  enabled: true
  servers:
    - name: gitlab
      config_file: .claude-code/mcp-config.json

settings:
  model: "${CLAUDE_MODEL:-claude-sonnet-4}"
  permission_mode: "${CLAUDE_PERMISSION_MODE:-viewOnly}"
  debug: ${CLAUDE_DEBUG:-false}
EOF

log_info "MCP server configuration created at $CLAUDE_DIR/"

# Validate configuration
if [ -f "$CLAUDE_DIR/mcp-config.json" ] && [ -f "$CLAUDE_DIR/config.yml" ]; then
    log_info "✅ MCP server setup completed successfully"
else
    log_error "Failed to create configuration files"
    exit 1
fi

# Test MCP server connectivity (optional)
if [ "${MCP_TEST_CONNECTION:-false}" = "true" ]; then
    log_info "Testing MCP server connectivity..."

    # Simple API test
    HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
        --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}")

    if [ "$HTTP_STATUS" = "200" ]; then
        log_info "✅ GitLab API connection successful"
    else
        log_warn "⚠ GitLab API returned status $HTTP_STATUS"
    fi
fi

log_info "MCP server ready for Claude Code operations"
